name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:

  gitversion:
    runs-on: ubuntu-latest
    outputs:
      MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}
      PreReleaseTag: ${{ steps.gitversion.outputs.PreReleaseTag }}
      SemVer: ${{ steps.gitversion.outputs.SemVer }}
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true

  build-and-push:
    needs: gitversion
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: otel-demo-data-api
      VERSION: ${{ needs.gitversion.outputs.MajorMinorPatch }}

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 5: Docker login
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 6: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .

      # Step 7: Push the Docker image to the registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
